# Generated by Django 4.1.6 on 2023-02-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nou', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('sal', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
